### ISSUE TITLE
Asset license/reuse?

### ISSUE THREAD

**Issue by nightblade9** [mightymochi/Godot-3-Masking-Methods#1]
Hi there, I'm the maintainer of the [Godot Fancy Scene Changes](https://github.com/nightblade9/godot-fancy-scene-changes) assetlib. I would like to incorporate two of the assets from the root of your repo (`swirl.jpg` and `tile_reveal.png`) into my library. Is that okay with you, and/or what are the license on these? (Do I need to credit you or someone else in my repo credits?)

Thanks for making this repo, it's really really useful!

**Comment by mightymochi** [comment]
I took the swirl.jpg out of my github as it was left in there by accident. That came from https://godotshaders.com/shader/simple-2d-transition/ , so I'd suggest contacting that user. 

As for the tile_reveal.png, sure you can use that. I created that from scratch and I'll put it out there as free to use. I guess I need to look into what sort of license is free and open to attach to things. It would be great to get a credit for it though as I did spend a fair amount of time creating it. 

I'm interested to check out your assetlib to see how you're implementing things.

**Comment by nightblade9** [comment]
> I guess I need to look into what sort of license is free and open to attach to things. It would be great to get a credit for it though as I did spend a fair amount of time creating it.

I think users typically pick MIT (free, no strings attached, commercial or non-commercial, no credit required) for things that are free-free. If you prefer attribution, you can use one of the Creative Commons licenses. I can credit you either way.

> I'm interested to check out your assetlib to see how you're implementing things.

It's like the shader you described as "powerful," the one that fades from black and white. That's pretty much all I use, albeit I ship with a bunch of images as pre-existing fades. Also, my assetlib is focused around scene transitions, not so much masking.

**Comment by nightblade9** [comment]
I credited you in my repo README, let me know if that's good enough or if you want something else.

**Comment by mightymochi** [comment]
Good enough for me! Thanks.
